[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["cd facilitator && npm install"]

[phases.build]
cmds = ["cd facilitator && npm run build"]

[start]
cmd = "cd facilitator && npm run start"
