[package]
name = "payment"
edition = "2024"
license = "MIT"
authors = ["Pay402 Team"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
payment = "0x0"

[environments]
# Suibase workdirs (chain IDs populated on first publish)
localnet = "0x0"
testnet = "0x0"
devnet = "0x0"
mainnet = "0x0"
